//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_CHECKIFARRAYISSORTED_H
#define SIMPLE_CALCULATOR_CHECKIFARRAYISSORTED_H


class checkIfArrayIsSorted {

};


#endif //SIMPLE_CALCULATOR_CHECKIFARRAYISSORTED_H
