//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_CHECKIFNUMBERISPALINDROME_H
#define SIMPLE_CALCULATOR_CHECKIFNUMBERISPALINDROME_H


class checkIfNumberIsPalindrome {

};


#endif //SIMPLE_CALCULATOR_CHECKIFNUMBERISPALINDROME_H
