//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_COUNTDIGITSOFNUMBER_H
#define SIMPLE_CALCULATOR_COUNTDIGITSOFNUMBER_H


class countDigitsOfNumber {

};


#endif //SIMPLE_CALCULATOR_COUNTDIGITSOFNUMBER_H
