//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_FIBONACHINUMBERATNPOSITION_H
#define SIMPLE_CALCULATOR_FIBONACHINUMBERATNPOSITION_H


class FIbonachiNumberAtNposition {

};


#endif //SIMPLE_CALCULATOR_FIBONACHINUMBERATNPOSITION_H
