//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_MULTIPLICATIONOFMBYN_H
#define SIMPLE_CALCULATOR_MULTIPLICATIONOFMBYN_H


class multiplicationOfMbyN {

};


#endif //SIMPLE_CALCULATOR_MULTIPLICATIONOFMBYN_H
