//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_PRINTNUMBERSFROM1TON_H
#define SIMPLE_CALCULATOR_PRINTNUMBERSFROM1TON_H


class printNumbersFrom1ToN {

};


#endif //SIMPLE_CALCULATOR_PRINTNUMBERSFROM1TON_H
