//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_OVERRIDEFUNCTIONS_H
#define SIMPLE_CALCULATOR_OVERRIDEFUNCTIONS_H


class overrideFunctions {

};


#endif //SIMPLE_CALCULATOR_OVERRIDEFUNCTIONS_H
