//
// Created by PC on 12/4/2024.
//

#ifndef SIMPLE_CALCULATOR_TEMPLATEWITHMANYTYPES_H
#define SIMPLE_CALCULATOR_TEMPLATEWITHMANYTYPES_H


class templateWithManyTypes {

};


#endif //SIMPLE_CALCULATOR_TEMPLATEWITHMANYTYPES_H
