//
// Created by PC on 2/20/2025.
//

#ifndef SIMPLE_CALCULATOR_SIMPLESTLINKEDLIST_H
#define SIMPLE_CALCULATOR_SIMPLESTLINKEDLIST_H


class SimplestLinkedlist {

};


#endif //SIMPLE_CALCULATOR_SIMPLESTLINKEDLIST_H
