//
// Created by PC on 3/13/2025.
//

#ifndef SIMPLE_CALCULATOR_ADJACENTMATRIXWEIGHTEDGRAPH_H
#define SIMPLE_CALCULATOR_ADJACENTMATRIXWEIGHTEDGRAPH_H


class AdjacentMatrixWeightedGraph {

};


#endif //SIMPLE_CALCULATOR_ADJACENTMATRIXWEIGHTEDGRAPH_H
